### ISSUE TITLE
Weird color behaviour

### ISSUE THREAD

**Issue by mathsaey** [dbordak/telephone-line#54]
Telephone-line seems to be rendering my separator colors incorrectly.

Here's all of my config that's related to telephone-line:

```
(use-package telephone-line
  :ensure t
  :config
    (setq
      telephone-line-height 24
      telephone-line-primary-left-separator 'telephone-line-cubed-left
      telephone-line-primary-right-separator 'telephone-line-cubed-right
      telephone-line-secondary-left-separator 'telephone-line-cubed-hollow-left
      telephone-line-secondary-right-separator'telephone-line-cubed-hollow-right)

    (require 'telephone-line-config)
    (telephone-line-evil-config))
```

And here's a screenshot of the result:

<img width="222" alt="screen shot 2017-11-11 at 01 57 21" src="https://user-images.githubusercontent.com/1266349/32684436-d42fdf48-c683-11e7-8557-310fa86c3b47.png">

This seems to occur regardless of the theme I use. I'm pretty new to emacs though, so there is a pretty high chance that I made a mistake somewhere.

**Comment by dbordak** [comment]
That is odd, but sounds familiar... Are you on OSX? I seem to recall something about Emacs on OSX having screwed up colors in images (the color discrepancy in your image is between stuff that is rendered as text and stuff that is rendered as images)

**Comment by mathsaey** [comment]
That seems to be the problem I'm dealing with. Adding `(setq ns-use-srgb-colorspace nil)` to my config seems to fix the issue. Unfortunately, that just disables srgb colors everywhere, which makes everything look rather ugly.

Thanks for the pointer! I'll see if I can find a better workaround and post it here if I find something.

**Comment by dbordak** [comment]
I looked into it a bit, there's a patched version of emacs over here: https://github.com/railwaycat/homebrew-emacsmacport

I can also patch it within telephone-line, but considering how there's something like this unpatched in upstream, shouldn't there be other things fixed in that? I don't know if it's right to fix one bug to help people use the more buggy version, if you know what I mean.

**Comment by mathsaey** [comment]
> I can also patch it within telephone-line, but considering how there's something like this unpatched in upstream, shouldn't there be other things fixed in that? I don't know if it's right to fix one bug to help people use the more buggy version, if you know what I mean.

Powerline (and some other plugins) seem to have built-in workarounds, but I completely agree with your approach.

I spent some more time looking into it too, and it seems that building standard homebrew emacs with the `--with-libsrvg` flag also solves the issue.

Thanks for looking into this!

**Comment by mathsaey** [comment]
It seems using `--with-libsrvg` didn't fix it after all, I was just being stupid. Nonetheless, I'll leave this issue closed, since it seems to be an upstream problem. If I find some solution (that doesn't rely on the mac port) I'll post it here.

**Comment by seagle0128** [comment]
`(setq ns-use-srgb-colorspace nil)` works for me as a workaround.

In `powerline`, colors are converted from sRGB color space to Apple RGB on macOS.

```elisp
(defun pl/color-srgb-to-apple-rgb (red green blue)
  "Convert RED GREEN BLUE colors from sRGB color space to Apple RGB.
RED, GREEN and BLUE should be between 0.0 and 1.0, inclusive."
  (apply 'pl/color-xyz-to-apple-rgb (color-srgb-to-xyz red green blue)))

(defun pl/hex-color (color)
  "Get the hexadecimal value of COLOR."
  (when color
    (let ((srgb-color (color-name-to-rgb color)))
      (if powerline-image-apple-rgb
          (apply 'color-rgb-to-hex (apply 'pl/color-srgb-to-apple-rgb srgb-color))
        (apply 'color-rgb-to-hex srgb-color)))))
```
